name: Triggered on push

on: 
  push:
    paths:
      - "ChildCare.py"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: python -m test_ChildCare
