# This workflow will test the python modules 
# when codes are modified

name: Test Python Lib

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: |
          python -m ./ChildCare_Tests/test_ChildCare
          python -m ./ChildCare_Tests/test_ChildCareAPI
